/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes;

import org.junit.Test;

import java.io.IOException;

import static org.junit.Assert.*;

public class AppTest {
    @Test public void FileToStringAndParsTest() throws IOException {

        ParseString parser = new ParseString();
        parser.convertString("src/test/resources/test.json");

        assertEquals("FileToStringAndParsTest should return S.A. McAuley","S.A. McAuley",parser.getParsedData()[0].getAuthor());
        assertEquals("FileToStringAndParsTest should return George Orwell","George Orwell",parser.getParsedData()[1].getAuthor());
    }

    @Test public void searchByAuthorTest() throws IOException {

        ParseString parser = new ParseString();
        parser.convertString("src/test/resources/test.json");

        parser.searchByAuthor("S.A. McAuley");
        assertEquals("searchByAuthorTest should return S.A. McAuley","S.A. McAuley",parser.getQuote().getAuthor());

        parser.searchByAuthor("George Orwell");
        assertEquals("FileToStringAndParsTest should return George Orwell","George Orwell",parser.getQuote().getAuthor());
    }
}
