/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes;

import com.google.gson.Gson;

import java.io.IOException;
import java.io.Reader;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.util.Random;
//import java.util.Map;

public class App {
    public static void main(String[] args) throws IOException {
        if (args.length > 0){
            ParseString parser = new ParseString();
            parser.convertString("src/main/resources/recentquotes.json");
            if (parser.searchByAuthor(args[0])){
                System.out.println(parser.getQuote());
            }else {
                System.out.println("Couldn't find " + args[0]);
            }
            return;
        }
//
        ParseString parser = new ParseString();
//        parser.convertString("src/main/resources/recentquotes.json");
        parser.httpGetQuote();
//        for (Quote q : test.getParsedData()) {
//            System.out.println(q.toString());
//        }
//        int random = randomQuote(parser.getParsedData().length);
//
//        System.out.println("AT INDEX "+random + " " +parser.getParsedData()[random]);


    }

    public static int randomQuote(int length){
        Random random = new Random();

        return random.nextInt(length - 1) ;
    }


}
